version: "3.8"

services:
  db:
    image: postgres:16
    container_name: biblioteca-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
